In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [3]:
df.head()

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.get_weights()

[array([[ 1.0361305 ,  0.33021998],
        [ 0.61806536, -0.07320929]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.3176955 ],
        [-0.13353407]], dtype=float32),
 array([0.], dtype=float32)]

In [10]:
new_weights =  [np.array([[0.1 , 0.1],
        [ 0.1,  0.1 ]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1],
        [0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [11]:
model.set_weights(new_weights)

In [13]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [18]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [19]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 27.8873
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 27.5898
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 27.2429
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 26.9183
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 26.5464
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 26.1937
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 25.8427
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 25.4638
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 25.0701
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 24.6620
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 24.2228
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 23.8055 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 23.3833
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 22.9298
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 22.4914
Epoch 16/75
4/4 ━━

In [20]:
model.get_weights()

[array([[0.3736588 , 0.3736588 ],
        [0.36557075, 0.36557075]], dtype=float32),
 array([0.27233112, 0.27233112], dtype=float32),
 array([[0.3729169],
        [0.3729169]], dtype=float32),
 array([0.20477335], dtype=float32)]